[theme]
primaryColor = "#5681d0"  # 메인 색상 (orange)
backgroundColor = "#212750"  # 배경 색상 (navy)
secondaryBackgroundColor = "#1a1a3d"  # 보조 배경 색상 (사이드바)
textColor = "#f8f8f2"  # 텍스트 색상

[default]
API_KEY = "GgLjau4j2h25nVd9tQzIYNzGT1uH8X56"